" VIM CONFIGURATION 

" Essential
set nocompatible                    " Enter the third millenium
syntax enable                       " Enable syntax highlighting
filetype plugin indent on           " Enable filetype syntax and indentation

" Editing
set softtabstop=4                   " Convert new tabs to four spaces
set shiftwidth=4
set expandtab
set backspace=indent,eol,start      " Make vim backspace behave as expected
set autoindent                      " Enable automatic indentation
set wrap linebreak                  " Enable soft wordwrap
set formatoptions=tcrqwan1j         " Formatting options, as follows:
                                    " t - Auto-wrap to 79
                                    " c - Auto-wrap comments with leader
                                    " r - Auto-insert comment leader with Enter
                                    " q - Allow 'gq' to format comments
                                    " w - Whitespace continues paragraphs
                                    " a - Auto-format paragraphs / pasted
                                    " n - Recognize numbered list
                                    " 1 - Don't line on one-letter words
                                    " j - Remove comment leaders when joining

" UI
set number                          " Enable line numbers
set showcmd                         " Show last command at bottom
set showmatch                       " Show matching brackets, etc.
set colorcolumn=80                  " Show 80-column line marker
set cursorline                      " Underline current line
set wildmenu                        " Show visual tab suggestions for commands
set incsearch                       " Search as characters are entered
set ignorecase                      " Ignore case in searches
set hidden                          " Allow buffers to be left without saving
set splitright                      " Splits windows to the right by default
colorscheme slate
highlight Comment cterm=italic gui=italic

" Backups
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set writebackup

" Bindings
let mapleader=","                   " Set leader (shortcut) key to comma

" Save session with ,s
nnoremap <leader>s :mksession<CR>

" Close with saving (,c) or without saving (,xx)
nnoremap <leader>c ZZ
nnoremap <leader>xx ZQ

" Edit and source various config files
nnoremap <leader>ea :e ~/.zsh/zalias<CR>
nnoremap <leader>eh :e ~/.dot/ahk/hotkeys.ahk<CR>
nnoremap <leader>em :e ~/.dot/etc/mpv/mpv.conf<CR>
nnoremap <leader>ev :e ~/.vimrc<CR>
nnoremap <leader>ez :e ~/.zshrc<CR>
nnoremap <leader>sv :source ~/.vimrc<CR>

" Functions

" Always open help and shells in vertically split windows
cnoreabbrev <expr> help ((getcmdtype() is# ':' && getcmdline() is# 'help')?('vert help'):('help'))
cnoreabbrev <expr> h ((getcmdtype() is# ':'&& getcmdline() is# 'h')?('vert help'):('h'))
cnoreabbrev <expr> ter ((getcmdtype() is# ':' && getcmdline() is# 'ter')?('vert ter'):('ter'))

" GUI
set mouse=a                         " Enable support for mouse and scrollwheel
map <ScrollWheelUp> 3k
map <ScrollWheelDown> 3j
